FROM node:alpine

WORKDIR '/app'
COPY ./package.json ./

# To Fix Permissions for Packages
RUN npm config set unsafe-perm true

RUN npm install
RUN mkdir /app/node_modules/.cache && chmod -R 777 /app/node_modules/.cache
COPY . .
CMD ["npm", "run", "start"]
