sudo: required
services:
  - docker

before_install:
  - docker build -t ademoladebayo/complexweb-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ademoladebayo/complexweb-react-test npm run test

after_success:
  - docker build -t ademoladebayo/multi-client ./client
  - docker build -t ademoladebayo/multi-nginx  ./nginx
  - docker build -t ademoladebayo/multi-server ./server
  - docker build -t ademoladebayo/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ademoladebayo/multi-client
  - docker push ademoladebayo/multi-nginx
  - docker push ademoladebayo/multi-server
  - docker push ademoladebayo/multi-worker
