sudo: required
services:
  - docker

before_install:
  - docker build -t adereactive/complexweb-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adereactive/complexweb-react-test npm run test

after_success:
  - docker build -t adereactive/multi-client ./client
  - docker build -t adereactive/multi-nginx  ./nginx
  - docker build -t adereactive/multi-server ./server
  - docker build -t adereactive/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push adereactive/multi-client
  - docker push adereactive/multi-nginx
  - docker push adereactive/multi-server
  - docker push adereactive/multi-worker


deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-012119841372"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
